export default interface IPatient {
    patientId: number;
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    sex: string ;
    sexAtBirth: string ;
    preferredPronouns: string ;
    genderIdentity: string;
    suffix: string;
    maritalStatus: string;
    race: string;
    raceId: number ;
    ethnicity: string;
    ethnicityId: number ;
    language: string;
    languageId: number;
    phoneNumber: string;
    email: string;
    addressLine1: string;
    addressLine2: string;
    city: string;
    state: string;
    zipCode: string;
    reasonForVisit: string;
    visitTime: string;
    primaryCareProvider: string;
    registrationId: number;
    regionId: number;
    hospitalId: number;
    status: string;
    personId: number;
  }